const rooms=require('./rooms'); const {ensureStats}=require('./store');
const clone=v=>JSON.parse(JSON.stringify(v)); const ids=v=>[...new Set((Array.isArray(v)?v:[v]).filter(x=>x!=null).map(String))].sort();
const getRoom=c=>rooms[c]||null;
function createRoom(code,q){rooms[code]={quizTitle:q.title,questions:clone(q.questions),originalQuestions:clone(q.questions),timeLimit:q.timeLimit||30,creatorId:q.creatorId,organizers:new Set([q.creatorId]),players:new Map(),scores:{},answers:{},answered:{},participated:new Set(),currentQuestionIndex:-1,status:'waiting',startedAt:null,finishedAt:null,questionStartTime:null,timer:null,advancePending:false,resultSaved:false}}
function addPlayer(code,user){const r=rooms[code];if(!r)return{error:'Комната не найдена'};if(r.status==='active'&&!r.players.has(user.id))return{error:'Игра уже началась'};const p=r.players.get(user.id)||{};r.players.set(user.id,{id:user.id,name:user.name||p.name||'Игрок',avatar_url:user.avatar_url||p.avatar_url||''});if(r.scores[user.id]==null)r.scores[user.id]=0;if(r.answered[user.id]==null)r.answered[user.id]=false;return{success:true}}
function removePlayer(code,userId){const r=rooms[code];if(!r)return;if(r.status==='active')return;r.players.delete(userId);delete r.scores[userId];delete r.answered[userId];delete r.answers[userId];if(userId!==r.creatorId)r.organizers.delete(userId)}
function publicQuestion(q,reveal=false){if(!q)return null;return{id:q.id,text:q.text,image_url:q.image_url||null,multiple:q.multiple===true||q.options.filter(o=>o.is_correct).length>1,timeLimit:q.timeLimit,options:q.options.map(o=>({id:o.id,text:o.text,...(reveal?{is_correct:!!o.is_correct}:{})}))}}
function leaderboard(r){let rank=0,last=null;return[...r.players.values()].map(p=>({user_id:p.id,name:p.name,avatar_url:p.avatar_url,score:+(r.scores[p.id]||0).toFixed(2)})).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name)).map((p,i)=>{if(p.score!==last){rank=i+1;last=p.score}return{...p,place:rank}})}
function getGameState(code,userId){const r=rooms[code];if(!r)return null;const q=r.questions[r.currentQuestionIndex]||null;const limit=q?.timeLimit||r.timeLimit||30;const timeLeft=r.questionStartTime&&q?Math.max(0,Math.ceil(limit-(Date.now()-r.questionStartTime)/1000)):null;const ans=r.answers[userId];return{roomCode:code,status:r.status,players:[...r.players.values()].map(p=>({...p,isCreator:p.id===r.creatorId,isOrganizer:r.organizers.has(p.id)})),scores:r.scores,currentQuestion:publicQuestion(q,r.status==='finished'),currentQuestionIndex:r.currentQuestionIndex,totalQuestions:r.questions.length,isCreator:r.creatorId===userId,isOrganizer:r.organizers.has(userId),timeLeft,questionEndsAt:r.questionStartTime? r.questionStartTime+limit*1000:null,hasAnswered:!!r.answered[userId],selectedOptionIds:ans?.optionIds||[],answerResult:ans?{isCorrect:ans.isCorrect,points:+ans.points.toFixed(2)}:null,quizTitle:r.quizTitle,creatorId:r.creatorId,organizers:[...r.organizers],leaderboard:r.status==='finished'?leaderboard(r):null}}
function emitState(io,code){const r=rooms[code];if(!r)return;for(const s of io.sockets.adapter.rooms.get(code)||[]){const sock=io.sockets.sockets.get(s);if(sock?.data.user) sock.emit('game_state',getGameState(code,sock.data.user.id))}}
function schedule(code,io,d=900){const r=rooms[code];if(!r||r.advancePending)return;r.advancePending=true;clearTimeout(r.timer);r.timer=setTimeout(()=>{r.advancePending=false;advanceQuiz(code,io)},d)}
function startQuiz(code,io){const r=rooms[code];if(!r)return{error:'Комната не найдена'};if(r.status!=='waiting')return{error:'Сначала перезапустите квиз'};if(!r.questions.length)return{error:'Нет вопросов'};if(!r.players.size)return{error:'Нет участников'};r.status='active';r.currentQuestionIndex=0;r.startedAt=Date.now();r.finishedAt=null;r.resultSaved=false;r.scores={};r.answers={};r.answered={};r.participated=new Set();for(const id of r.players.keys()){r.scores[id]=0;r.answered[id]=false}r.questionStartTime=Date.now();const q=r.questions[0],limit=q.timeLimit||r.timeLimit;clearTimeout(r.timer);r.timer=setTimeout(()=>advanceQuiz(code,io),limit*1000+250);emitState(io,code);return{success:true}}
function submitAnswer(code,userId,qid,optionIds,io){const r=rooms[code];if(!r)return{error:'Комната не найдена'};if(!r.players.has(userId))return{error:'Сначала войдите в комнату'};if(r.status!=='active')return{error:'Квиз не активен'};const q=r.questions[r.currentQuestionIndex];if(!q||String(q.id)!==String(qid))return{error:'Неверный вопрос'};const limit=q.timeLimit||r.timeLimit;if(Date.now()-r.questionStartTime>limit*1000)return{error:'Время вышло'};if(r.answered[userId])return{error:'Ответ уже отправлен'};const selected=ids(optionIds),valid=new Set(q.options.map(o=>String(o.id)));if(!selected.length||selected.some(x=>!valid.has(x)))return{error:'Неверный вариант ответа'};const correct=ids(q.options.filter(o=>o.is_correct).map(o=>o.id));if(!q.multiple&&correct.length<=1&&selected.length!==1)return{error:'Можно выбрать только один вариант'};const cs=selected.filter(x=>correct.includes(x)).length,ws=selected.length-cs,exact=selected.length===correct.length&&selected.every(x=>correct.includes(x));const points=exact?1:Math.max(0,cs/correct.length-ws/Math.max(1,q.options.length-correct.length));r.scores[userId]=(r.scores[userId]||0)+points;r.answered[userId]=true;r.answers[userId]={questionId:q.id,optionIds:selected,isCorrect:exact,points};r.participated.add(userId);const st=ensureStats(userId);st.totalAnswers++;if(exact)st.correctAnswers++;if([...r.players.keys()].every(id=>r.answered[id]))schedule(code,io);emitState(io,code);return{isCorrect:exact,points:+points.toFixed(2)}}
function saveResults(r,code){if(r.resultSaved)return;const board=leaderboard(r).filter(p=>r.participated.has(p.user_id));const top=board[0]?.score;for(const p of board){const st=ensureStats(p.user_id);st.gamesPlayed++;const won=p.score===top;if(won)st.wins++;st.history.unshift({roomCode:code,quizTitle:r.quizTitle,date:new Date().toISOString(),score:p.score,place:p.place,won});st.history=st.history.slice(0,50)}r.resultSaved=true}
function advanceQuiz(code,io){const r=rooms[code];if(!r||r.status!=='active')return;r.currentQuestionIndex++;r.advancePending=false;if(r.currentQuestionIndex>=r.questions.length){r.status='finished';r.finishedAt=Date.now();r.questionStartTime=null;clearTimeout(r.timer);r.timer=null;saveResults(r,code);emitState(io,code);io.to(code).emit('quiz_finished');return}const q=r.questions[r.currentQuestionIndex],limit=q.timeLimit||r.timeLimit;r.questionStartTime=Date.now();r.answers={};for(const id of r.players.keys())r.answered[id]=false;clearTimeout(r.timer);r.timer=setTimeout(()=>advanceQuiz(code,io),limit*1000+250);emitState(io,code)}
function restartQuiz(code,io){const r=rooms[code];if(!r)return{error:'Комната не найдена'};clearTimeout(r.timer);r.status='waiting';r.currentQuestionIndex=-1;r.questions=clone(r.originalQuestions);r.scores={};r.answers={};r.answered={};r.participated=new Set();r.startedAt=r.finishedAt=r.questionStartTime=r.timer=null;r.advancePending=r.resultSaved=false;for(const id of r.players.keys()){r.scores[id]=0;r.answered[id]=false}emitState(io,code);io?.to(code).emit('quiz_restarted');return{success:true}}
function setOrganizer(code,actor,target,en){const r=rooms[code];if(!r)return{error:'Комната не найдена'};if(!r.organizers.has(actor))return{error:'Недостаточно прав'};if(!r.players.has(target))return{error:'Игрок не найден'};if(target===r.creatorId&&!en)return{error:'Создателя нельзя лишить прав'};en?r.organizers.add(target):r.organizers.delete(target);return{success:true}}
module.exports={getRoom,createRoom,addPlayer,removePlayer,getGameState,emitState,startQuiz,submitAnswer,advanceQuiz,restartQuiz,setOrganizer};
